### ISSUE TITLE
A few missing pieces

### ISSUE THREAD

**Issue by sheeley** [kossnocorp/babel-hubot#2]
Using Node 5, the peer dependencies don't install, so I had to add coffee-script to the install as well, plus some additional changes for Babel 6:

```
npm install babel-hubot babel-core coffee-script babel-preset-es2015 --save
```

As well as putting this in `.babelrc`

```
{
  "presets": ["es2015"]
}
```

**Comment by kossnocorp** [comment]
@sheeley makes sense, I will add this to docs.

**Comment by kossnocorp** [comment]
Thanks!
